### ISSUE TITLE
"LayerNormKernelImpl" not implemented for 'Half'

### ISSUE THREAD

**Issue by ntrpnr** [ArEnSc/Production-RWKV#19]
I tried the sample code provided and got an error.

```
tokenizer = RWKVTokenizer.default()
model = RWKVRNN4NeoForCausalLM.from_pretrained("RWKV-4-430M")
context_input_ids = tokenizer.encode(prompt).ids
model.warmup_with_context(context=context_input_ids)

def callback(ind):
    token = tokenizer.decode([ind],skip_special_tokens=False)
    print(token,end="")

ctx = model.generate(input_ids=[],streaming_callback=callback,max_length=max_length,repetition_penalty=repetition_penalty,temperature=temperature,stop_on_eos=True)
result = tokenizer.decode(ctx,skip_special_tokens=False) 
```

```
Traceback (most recent call last):
  File "handle_request", line 81, in handle_request
    FutureStatic,
  File "server.py", line 36, in inference
    output = user_src.inference(model_inputs)
  File "/app.py", line 33, in inference
    model.warmup_with_context(context=context_input_ids)
  File "/opt/conda/lib/python3.8/site-packages/prwkv/rwkvrnnmodel.py", line 131, in warmup_with_context
    init_state = self.model.forward(x, init_state, preprocess_only=True)
  File "/opt/conda/lib/python3.8/site-packages/prwkv/modelrun.py", line 213, in forward
    x = self.LN(x, w.blocks[i].ln0)
  File "/opt/conda/lib/python3.8/site-packages/prwkv/modelrun.py", line 114, in LN
    return F.layer_norm(x, (self.args.n_embd,), weight=w.weight, bias=w.bias)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2486, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'
```

**Comment by ArEnSc** [comment]
yeah been too busy to fix this gonna give this a shot now

**Comment by ArEnSc** [comment]
@ntrpnr 5fa306ba63477c26135feb3461ce33af349a70ec everything after this commit broke not sure exactly why just yet but will figure out after I do my day job .

**Comment by ArEnSc** [comment]
you are safe to use version='0.1.6 you won't get half precision memory usage however

**Comment by ArEnSc** [comment]
ok that's right, so you cannot start off using float 16 mainly because pytorch doesn't support that for layer norm for cpu I believe afaik, basically I need to put in code that will prevent and assert this if this scenario happens

**Comment by ArEnSc** [comment]
Resolved @ntrpnr
